const LEDGER_CONNECTION_CHECK = 'LEDGER_CONNECTION_CHECK';
const LEDGER_CONNECTION_STATUS = 'LEDGER_CONNECTION_STATUS';
const LEDGER_SIGNATURE_REQUEST = 'LEDGER_SIGNATURE_REQUEST';
const LEDGER_SIGNATURE_RESPONSE = 'LEDGER_SIGNATURE_RESPONSE';

module.exports = {
  LEDGER_CONNECTION_CHECK,
  LEDGER_CONNECTION_STATUS,
  LEDGER_SIGNATURE_REQUEST,
  LEDGER_SIGNATURE_RESPONSE,
};
