export const LEDGER_CONNECTION_CHECK = 'LEDGER_CONNECTION_CHECK';
export const LEDGER_CONNECTION_STATUS = 'LEDGER_CONNECTION_STATUS';
export const LEDGER_SIGNATURE_REQUEST = 'LEDGER_SIGNATURE_REQUEST';
export const LEDGER_SIGNATURE_RESPONSE = 'LEDGER_SIGNATURE_RESPONSE';
